# Generated by Django 3.1.5 on 2021-02-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['-value'], 'verbose_name': 'Звёзды рейтинга', 'verbose_name_plural': 'Звёзды рейтинга'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='is_draft',
            field=models.BooleanField(default=True, verbose_name='Черновик'),
        ),
    ]
